// Date: 3/23/2014 5:27:35 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer Head;
    ModelRenderer Body;
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Tail;
    ModelRenderer Ear1;
    ModelRenderer Ear2;
    ModelRenderer Nose;
  
  public ModelNew()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(-5F, -7F, -7F, 10, 10, 8);
      Head.setRotationPoint(0F, 31F, -12F);
      Head.setTextureSize(128, 64);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 36, 0);
      Body.addBox(-6F, -6F, -12F, 12, 12, 26);
      Body.setRotationPoint(0F, 32F, 0F);
      Body.setTextureSize(128, 64);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Leg1.mirror = true;
      Leg1 = new ModelRenderer(this, 0, 46);
      Leg1.addBox(-2F, 0F, -2F, 4, 10, 4);
      Leg1.setRotationPoint(-3F, 38F, 10F);
      Leg1.setTextureSize(128, 64);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg1.mirror = false;
      Leg2 = new ModelRenderer(this, 0, 46);
      Leg2.addBox(-2F, 0F, -2F, 4, 10, 4);
      Leg2.setRotationPoint(3F, 38F, 10F);
      Leg2.setTextureSize(128, 64);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg3.mirror = true;
      Leg3 = new ModelRenderer(this, 0, 46);
      Leg3.addBox(-2F, 0F, -2F, 4, 10, 4);
      Leg3.setRotationPoint(-3F, 38F, -8F);
      Leg3.setTextureSize(128, 64);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Leg3.mirror = false;
      Leg4 = new ModelRenderer(this, 0, 46);
      Leg4.addBox(-2F, 0F, -2F, 4, 10, 4);
      Leg4.setRotationPoint(3F, 38F, -8F);
      Leg4.setTextureSize(128, 64);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Tail = new ModelRenderer(this, 0, 18);
      Tail.addBox(-4F, 0F, -4F, 8, 20, 8);
      Tail.setRotationPoint(0F, 30F, 12F);
      Tail.setTextureSize(128, 64);
      Tail.mirror = true;
      setRotation(Tail, 1.047198F, 0F, 0F);
      Ear1 = new ModelRenderer(this, 36, 12);
      Ear1.addBox(-6F, -11F, -2F, 4, 4, 2);
      Ear1.setRotationPoint(0F, 31F, -12F);
      Ear1.setTextureSize(128, 64);
      Ear1.mirror = true;
      setRotation(Ear1, 0F, 0F, 0F);
      Ear2.mirror = true;
      Ear2 = new ModelRenderer(this, 36, 12);
      Ear2.addBox(2F, -11F, -2F, 4, 4, 2);
      Ear2.setRotationPoint(0F, 31F, -12F);
      Ear2.setTextureSize(128, 64);
      Ear2.mirror = true;
      setRotation(Ear2, 0F, 0F, 0F);
      Ear2.mirror = false;
      Nose = new ModelRenderer(this, 36, 0);
      Nose.addBox(-2F, -2F, -12F, 4, 4, 8);
      Nose.setRotationPoint(0F, 31F, -12F);
      Nose.setTextureSize(128, 64);
      Nose.mirror = true;
      setRotation(Nose, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Head.render(f5);
    Body.render(f5);
    Leg1.render(f5);
    Leg2.render(f5);
    Leg3.render(f5);
    Leg4.render(f5);
    Tail.render(f5);
    Ear1.render(f5);
    Ear2.render(f5);
    Nose.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
