// Date: 3/1/2014 8:45:59 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelIceElemental extends ModelBase
{
  //fields
    ModelRenderer Head;
    ModelRenderer ArmR;
    ModelRenderer ArmL;
    ModelRenderer Torso;
    ModelRenderer Waist;
    ModelRenderer Ankle;
    ModelRenderer SpikeR;
    ModelRenderer SpikeL;
    ModelRenderer SpikeM;
  
  public ModelIceElemental()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(-3F, -8F, -4F, 6, 8, 8);
      Head.setRotationPoint(0F, 1F, 2F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      ArmR.mirror = true;
      ArmR = new ModelRenderer(this, 48, 16);
      ArmR.addBox(-3F, -2F, -2F, 4, 12, 4);
      ArmR.setRotationPoint(-5F, 3F, 2F);
      ArmR.setTextureSize(64, 32);
      ArmR.mirror = true;
      setRotation(ArmR, -0.3141593F, 0F, 0F);
      ArmR.mirror = false;
      ArmL = new ModelRenderer(this, 48, 16);
      ArmL.addBox(-1F, -2F, -2F, 4, 12, 4);
      ArmL.setRotationPoint(5F, 3F, 2F);
      ArmL.setTextureSize(64, 32);
      ArmL.mirror = true;
      setRotation(ArmL, -0.3141593F, 0F, 0F);
      Torso = new ModelRenderer(this, 20, 16);
      Torso.addBox(-4F, 1F, -2F, 8, 10, 6);
      Torso.setRotationPoint(0F, 0F, 1F);
      Torso.setTextureSize(64, 32);
      Torso.mirror = true;
      setRotation(Torso, 0F, 0F, 0F);
      Waist = new ModelRenderer(this, 0, 16);
      Waist.addBox(-3F, 0F, -2F, 6, 10, 4);
      Waist.setRotationPoint(0F, 10F, 3F);
      Waist.setTextureSize(64, 32);
      Waist.mirror = true;
      setRotation(Waist, -0.6283185F, 0F, 0F);
      Ankle = new ModelRenderer(this, 28, 0);
      Ankle.addBox(-2F, 3F, -10F, 4, 8, 4);
      Ankle.setRotationPoint(0F, 9F, 1F);
      Ankle.setTextureSize(64, 32);
      Ankle.mirror = true;
      setRotation(Ankle, 0.7853982F, 0F, 0F);
      SpikeR = new ModelRenderer(this, 44, 0);
      SpikeR.addBox(0F, 0F, 0F, 1, 6, 1);
      SpikeR.setRotationPoint(1.5F, 4F, 4F);
      SpikeR.setTextureSize(64, 32);
      SpikeR.mirror = true;
      setRotation(SpikeR, 2.024582F, 0.418879F, 0F);
      SpikeL = new ModelRenderer(this, 44, 0);
      SpikeL.addBox(-1F, 0F, 0F, 1, 6, 1);
      SpikeL.setRotationPoint(-1.5F, 4F, 4F);
      SpikeL.setTextureSize(64, 32);
      SpikeL.mirror = true;
      setRotation(SpikeL, 2.024582F, -0.418879F, 0F);
      SpikeM = new ModelRenderer(this, 44, 7);
      SpikeM.addBox(-0.5F, 0F, 1F, 1, 6, 1);
      SpikeM.setRotationPoint(0F, 4F, 3F);
      SpikeM.setTextureSize(64, 32);
      SpikeM.mirror = true;
      setRotation(SpikeM, 0.6632251F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Head.render(f5);
    ArmR.render(f5);
    ArmL.render(f5);
    Torso.render(f5);
    Waist.render(f5);
    Ankle.render(f5);
    SpikeR.render(f5);
    SpikeL.render(f5);
    SpikeM.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
